### ISSUE TITLE
bug:incomplete type is not allowed?

### ISSUE THREAD

**Issue by sutongkui** [mbartling/cuda-bvh#1]
The code is elegant and i am doing a project in which i need to construct bvh in parallel, and i used visual studio 2015 to compile it in windows, but there is an error just like this https://stackoverflow.com/questions/29269284/debugging-incomplete-type-errors-with-thrust
and i don't know how to fix it and i wonder if you have met the same problem?
thanks!

**Comment by mbartling** [comment]
I actually didn't try compiling against MSVC, so not sure if the libraries are slightly different. Do you generate the MSVC project with my cmake file?

Which versions of Thrust and Cuda are you compiling against?

**Comment by sutongkui** [comment]
yes, i used cmake to generate it and then compile with MSVC. I used cuda 8.0 and the corresponding thrust   to cuda 8.0(when i install cuda in windows, the thrust was added automatically).  Does The different version  leads to the bug?

**Comment by mbartling** [comment]
Hmm, it was just a thought. But I was able to get this to compile with Cuda 7.5+. Do you know which lines are causing the problem? Can you post the output + corresponding lines?

**Comment by sutongkui** [comment]
output:
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/include\thrust/detail/type_traits.h(607): error : incomplete type is not allowed
2>            detected during:
2>              instantiation of "thrust::detail::is_assignable_ns::is_assignable<T1, T2>::test [with T1=BoundingBox &, T2=thrust::reference<BoundingBox, thrust::pointer<BoundingBox, thrust::host_system_tag, thrust::use_default, thrust::use_default>, thrust::use_default>]" based on template arguments <BoundingBox &, thrust::reference<BoundingBox, thrust::pointer<BoundingBox, thrust::host_system_tag, thrust::use_default, thrust::use_default>, thrust::use_default>>
2>  (612): here
2>              instantiation of class "thrust::detail::is_assignable_ns::is_assignable<T1, T2> [with T1=BoundingBox &, T2=thrust::reference<BoundingBox, thrust::pointer<BoundingBox, thrust::host_system_tag, thrust::use_default, thrust::use_default>, thrust::use_default>]"
2>  (622): here
2>              instantiation of class "thrust::detail::is_assignable<T1, T2> [with T1=BoundingBox &, T2=thrust::reference<BoundingBox, thrust::pointer<BoundingBox, thrust::host_system_tag, thrust::use_default, thrust::use_default>, thrust::use_default>]"
2>  C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/include\thrust/system/detail/sequential/general_copy.h(41): here
2>              instantiation of class "thrust::system::detail::sequential::general_copy_detail::lazy_is_assignable<T1, T2> [with T1=thrust::iterator_reference<BoundingBox *>, T2=thrust::iterator_reference<thrust::detail::normal_iterator<thrust::pointer<BoundingBox, thrust::host_system_tag, thrust::use_default, thrust::use_default>>>]"
2>  (419): here
2>              instantiation of class "thrust::detail::eval_if<false, Then, Else> [with Then=thrust::detail::true_type, Else=thrust::system::detail::sequential::general_copy_detail::lazy_is_assignable<thrust::iterator_reference<BoundingBox *>, thrust::iterator_reference<thrust::detail::normal_iterator<thrust::pointer<BoundingBox, thrust::host_system_tag, thrust::use_default, thrust::use_default>>>>]"
2>  C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/include\thrust/system/detail/sequential/general_copy.h(61): here
2>              [ 34 instantiation contexts not shown ]
2>              instantiation of "OutputType thrust::system::cuda::detail::reduce(thrust::system::cuda::detail::execution_policy<DerivedPolicy> &, InputIterator, InputIterator, OutputType, BinaryFunction) [with DerivedPolicy=thrust::system::cuda::detail::tag, InputIterator=thrust::transform_iterator<minAccessor, thrust::device_ptr<BoundingBox>, Vec3f, thrust::use_default>, OutputType=Vec3f, BinaryFunction=minFunctor]"
2>  C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/include\thrust/detail/reduce.inl(71): here
2>              instantiation of "T thrust::reduce(const thrust::detail::execution_policy_base<DerivedPolicy> &, InputIterator, InputIterator, T, BinaryFunction) [with DerivedPolicy=thrust::system::cuda::detail::tag, InputIterator=thrust::transform_iterator<minAccessor, thrust::device_ptr<BoundingBox>, Vec3f, thrust::use_default>, T=Vec3f, BinaryFunction=minFunctor]"
2>  C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/include\thrust/system/detail/generic/transform_reduce.inl(48): here
2>              instantiation of "OutputType thrust::system::detail::generic::transform_reduce(thrust::execution_policy<ExecutionPolicy> &, InputIterator, InputIterator, UnaryFunction, OutputType, BinaryFunction) [with ExecutionPolicy=thrust::system::cuda::detail::tag, InputIterator=thrust::device_ptr<BoundingBox>, UnaryFunction=minAccessor, OutputType=Vec3f, BinaryFunction=minFunctor]"
2>  C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/include\thrust/detail/transform_reduce.inl(47): here
2>              instantiation of "OutputType thrust::transform_reduce(const thrust::detail::execution_policy_base<DerivedPolicy> &, InputIterator, InputIterator, UnaryFunction, OutputType, BinaryFunction) [with DerivedPolicy=thrust::system::cuda::detail::tag, InputIterator=thrust::device_ptr<BoundingBox>, UnaryFunction=minAccessor, OutputType=Vec3f, BinaryFunction=minFunctor]"
2>  C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/include\thrust/detail/transform_reduce.inl(67): here
2>              instantiation of "OutputType thrust::transform_reduce(InputIterator, InputIterator, UnaryFunction, OutputType, BinaryFunction) [with InputIterator=thrust::device_ptr<BoundingBox>, UnaryFunction=minAccessor, OutputType=Vec3f, BinaryFunction=minFunctor]"
2>  D:/Documents/Downloads/cuda-bvh-master/kernels/scene.cu(73): here
2>
2>  1 error detected in the compilation of "C:/Users/ADMINI~1/AppData/Local/Temp/tmpxft_00004440_00000000-11_scene.cpp1.ii".
2>CUSTOMBUILD : nvcc warning : The -std=c++11 flag is not supported with the configured host compiler. Flag will be ignored.
2>  scene.cu
2>  CMake Error at cuda_bvh_generated_scene.cu.obj.Debug.cmake:278 (message):
2>    Error generating file
2>    D:/Documents/Downloads/cuda-bvh-master/CMakeFiles/cuda_bvh.dir/kernels/Debug/cuda_bvh_generated_scene.cu.obj

and the bug is https://stackoverflow.com/questions/29269284/debugging-incomplete-type-errors-with-thrust

**Comment by mbartling** [comment]
Hmm this looks more like an issue with my build config. Can you try this out real fast? I have a full ray tracer implementation here https://github.com/mbartling/cuda-rt

I might have a more up to date version of the bvh there.

**Comment by sutongkui** [comment]
I tried the project above, but it failed again and has the same bug, now i decide to compile it in ubuntu.
anyway, very thanks!
